# Generated by Django 3.1.8 on 2021-04-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20210424_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_contests',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='all_contests',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='all_contests',
            name='winner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='utc',
            name='ticket',
            field=models.CharField(max_length=50),
        ),
    ]
